/api/v1/colormap/index:
      value: "ironbow"

/api/v1/config:
      contrast: 0.4
      gain: 20
      mirror_image: true

/api/v1/time: 
      now: 0

/api/v1/videotext:
      value: "some text"

/api/v1/streamtype: 
      value: 2

/api/v1/transponder:
      enable: true
      sonar_range: 3
